allowBuilds:
  esbuild: true
  unrs-resolver: true
savePrefix: ''
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vite-plus: 0.3.2
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
minimumReleaseAgeExclude:
  - oxlint-config-decent@5.0.0
