filters:
  allowlist:
    allow:
      - "/CHANGELOG\\.md$/"

rules:
  filters:
    - comments
  rules:
    terminology:
      exclude:
        - URL
        - website
        - markdown
        - Bug Fixes
        - eslint
        - typescript
        - DNs
        - id
