export enum ProtocolOperation {
  // Misc
  LDAP_VERSION_3 = 0x03,
  LBER_SET = 0x31,
  LDAP_CONTROLS = 0xa0,

  // Requests
  LDAP_REQ_BIND = 0x60,
  LDAP_REQ_UNBIND = 0x42,
  LDAP_REQ_SEARCH = 0x63,
  LDAP_REQ_MODIFY = 0x66,
  LDAP_REQ_ADD = 0x68,
  LDAP_REQ_DELETE = 0x4a,
  LDAP_REQ_MODRDN = 0x6c,
  LDAP_REQ_COMPARE = 0x6e,
  LDAP_REQ_ABANDON = 0x50,
  LDAP_REQ_EXTENSION = 0x77,

  // Responses
  LDAP_RES_BIND = 0x61,
  LDAP_RES_SEARCH_ENTRY = 0x64,
  LDAP_RES_SEARCH_REF = 0x73,
  LDAP_RES_SEARCH = 0x65,
  LDAP_RES_MODIFY = 0x67,
  LDAP_RES_ADD = 0x69,
  LDAP_RES_DELETE = 0x6b,
  LDAP_RES_MODRDN = 0x6d,
  LDAP_RES_COMPARE = 0x6f,
  LDAP_RES_EXTENSION = 0x78,
}
