name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    permissions:
      contents: write # To be able to publish a GitHub release
      issues: write # To be able to comment on released issues
      pull-requests: write # To be able to comment on released pull requests
      id-token: write # To enable use of OIDC for npm provenance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Generate certificates
        run: node tests/data/generate-certs.mjs

      - name: Start openldap container
        run: docker compose up -d --wait

      - name: Test
        run: npm test

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
